services:
  - type: web
    name: explorouen-backend
    env: node
    plan: free
    buildCommand: npm install && npx tsc
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: explorouen-db
          property: connectionString
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: RESEND_API_KEY
        sync: false
      - key: FROM_EMAIL
        value: contact@explorouen.onrender.com

databases:
  - name: explorouen-db
    databaseName: explorouen
    user: explorouen
    plan: free
